version: "3.8"
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn dev
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456789
      - DB_NAME=transport_app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: transport_app
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
